# Generated by Django 5.1.3 on 2025-04-22 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_fullname', models.CharField(blank=True, max_length=200)),
                ('shipping_phone', models.CharField(blank=True, max_length=20)),
                ('shipping_address1', models.CharField(blank=True, max_length=200)),
                ('shipping_address2', models.CharField(blank=True, max_length=200)),
                ('shipping_city', models.CharField(blank=True, max_length=200)),
                ('shipping_state', models.CharField(blank=True, max_length=200)),
                ('shipping_country', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
